INSERT INTO num (TRANSLATION, LANGUAGE, NUM)
VALUES
('eins', 'DE', 1),
('zwei','DE', 2),
('drei','DE', 3),
('vier','DE', 4),
('fünf','DE', 5),
('sechs','DE', 6),
('sieben','DE', 7),
('acht','DE', 8),
('neun','DE', 9),
('zehn','DE', 10),
('elf', 'DE', 11),
('zwölf','DE', 12),
('dreizehn','DE', 13),
('vierzehn','DE', 14),
('fünfzehn','DE', 15),
('sechzehn','DE', 16),
('siebzehn','DE', 17),
('achtzehn','DE', 18),
('neunzehn','DE', 19),
('zwanzig','DE', 20),
('einundzwanzig', 'DE', 21),
('zweiundzwanzig','DE', 22),
('dreiundzwanzig','DE', 23),
('vierundzwanzig','DE', 24),
('fünfundzwanzig','DE', 25),
('sechsundzwanzig','DE', 26),
('siebenundzwanzig','DE', 27),
('achtundzwanzig','DE', 28),
('neunundzwanzig','DE', 29),
('dreißig','DE', 30),
('one', 'EN', 1),
('two','EN', 2),
('three','EN', 3),
('four','EN', 4),
('five','EN', 5),
('six','EN', 6),
('seven','EN', 7),
('eight','EN', 8),
('nine','EN', 9),
('ten','EN', 10),
('eleven', 'EN', 11),
('twelve','EN', 12),
('thirteen','EN', 13),
('fourteen','EN', 14),
('fifteen','EN', 15),
('sixteen','EN', 16),
('seventeen','EN', 17),
('eighteen','EN', 18),
('nineteen','EN', 19),
('twenty','EN', 20),
('twenty-one', 'EN', 21),
('twenty-two','EN', 22),
('twenty-three','EN', 23),
('twenty-four','EN', 24),
('twenty-five','EN', 25),
('twenty-six','EN', 26),
('twenty-seven','EN', 27),
('twenty-eight','EN', 28),
('twenty-nine','EN', 29),
('thirty','EN', 30),
('un', 'FR', 1),
('deux', 'FR', 2),
('trois', 'FR', 3),
('quatre','FR', 4),
('cinq','FR', 5),
('six','FR', 6),
('sept','FR', 7),
('huit','FR', 8),
('neuf','FR', 9),
('dix','FR', 10),
('onze','FR', 11),
('douze','FR', 12),
('treize','FR', 13),
('quatorze','FR', 14),
('quinze','FR', 15),
('seize','FR', 16),
('dix-sept','FR', 17),
('dix-huit','FR', 18),
('dix-neuf','FR', 19),
('vingt','FR', 20),
('vingt et un','FR', 21),
('vingt-deux','FR', 22),
('vingt-trois','FR', 23),
('vingt-quatre','FR', 24),
('vingt-cinq','FR', 25),
('vingt-six','FR', 26),
('vingt-sept','FR', 27),
('vingt-huit','FR', 28),
('vingt-neuf','FR', 29),
('trente','FR', 30);

